---
title: "Import-chlo-samples"
author: "Brie Sherow"
date: "24/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
install.packages("splitstackshape")
library(splitstackshape) #text to column
library(stringr) #string split into column
library(tidyverse)
```
#create folder with the date of the observations and set this as the working directory
#move sample table, results table, txt file, and baseline to a folder called "metadata" 
#create folder with all of the measurement csvs called "samples"

```{r combine-csvs}

#set path **CHANGE THIS EVERY TIME TO MATCH DATED FOLDER**
mydir <- "chlo2611/samples"

#import the filenames as a list of values
filenames <- list.files(path=mydir, pattern="*.csv", full.names=TRUE) 

#use those values to populate a merged dataframe of all csv results
dat <- do.call("rbind", sapply(filenames, read.csv, simplify = FALSE)) 

#create a column from the name of each csv
dat$sample <- row.names(dat)

#clean column names to find sample number
dat <- dat %>%
  cSplit('sample', sep=".") %>% #text to column
  cSplit('sample_1', sep="/") %>% #get rid of "/"
  select(nm.s.A, X0.000000, sample_1_3) #remove irrelevant columns

#rename columns
names(dat) = c("wavelength", "absorbance", "Sample ID")

#long to wide
dat <- spread(dat, wavelength, absorbance)
```

```{r correct-order}

#import sample order **CHANGE EVERY TIME TO MATCH DATED FOLDER
sample_order <- read_csv("chlo2611/metadata/Results Table.csv")

#join absorbance values to sample order
df <- left_join(sample_order, dat, by="Sample ID")

#remove blank column
df <- select(df, -Description)

df <- df %>% separate(`Sample ID`, c("Code", "acid"))
```

```{r match-sampleID}

#import sample ID and dry weight
freezedry <- read_csv("freezedry.csv") #includes sample ID, dry weight

#change to character class to match with sample ID
freezedry$Code <- as.character(freezedry$Code)

#join sample ID and dry weight to sample order
chl_data <- left_join(df, freezedry, by="Code")

#correct the order of the columns
chl_data <- chl_data[, c(9,1,2,10,3,4,5,6,7,8)]

#write csv **CHANGE FILENAME TO DATE**
write_csv(chl_data, "chlo2611.csv")
```


